language: python

python:
    - "2.7"
    #- "pypy"
    #- "3.5"
    #- "pypy3"

install: 
    #- pip install python-coveralls
    - pip install codecov
    - pip install coverage
    - python setup.py develop

script:
    - pwd
    - test.pyutilib --cat=nightly --cov
    - ls -la * */*

after_success:
    - codecov
    #- coveralls
