language: python

python:
    - "2.7"
    #- "pypy"
    #- "3.5"
    #- "pypy3"

install: 
    - pip install xlrd
    - pip install openpyxl
    - pip install coverage
    - python setup.py develop

script:
    - test.pyutilib --cat=nightly --cov
    - mv ../.coverage .

after_success:
    - pip install codecov
    - codecov
