language: python

matrix:
  include:
    - python: "2.7"
      env: PYRO="Pyro"
    - python: "pypy"
      env: PYRO="Pyro"
    - python: "3.5"
      env: PYRO="Pyro4"
    - python: "pypy3"
      env: PYRO="Pyro4"

install: 
    - pip install pyyaml
    - pip install xlrd
    - pip install openpyxl
    - pip install $PYRO
    - pip install coverage
    - python setup.py develop

script:
    - test.pyutilib --cat=nightly --cov

after_success:
    - pip install codecov
    - cp ../.coverage .
    - codecov
    - pip install python-coveralls
    - cp ../.coverage .
    - coveralls
