language: python

python:
    - "2.7"
    - "pypy"
    - "3.5"
    - "pypy3"

install: 
    - pip install python-coveralls
    - pip install coverage
    - python setup.py develop

script:
    - pwd
    - test.pyutilib --cat=nightly --cov

after_success:
    - coveralls
