language: python

matrix:
  include:
    - python: "2.7"
      env: PYRO="Pyro"  YAML="pyyaml"
    - python: "2.7"
      env: PYRO="Pyro" JYTHON="org.python:jython-installer:2.5.3"
    #- python: "pypy"
    #  env: PYRO="Pyro"  YAML="pyyaml"
    #- python: "3.4"
    #  env: PYRO="Pyro4" YAML="pyyaml"
    #- python: "3.5"
    #  env: PYRO="Pyro4" YAML="pyyaml"
    #- python: "pypy3"
    #  env: PYRO="Pyro4" YAML="pyyaml"
    #- python: "3.5"
    #  env: PYRO="Pyro4" YAML=""

install: 
    - if [ -n "${YAML}" ]; then pip install pyyaml; fi
    - if [ -n "${JYTHON}" ]; then source install_jython.sh; fi
    - pip install --insecure unittest2
    - pip install --insecure xlrd
    - pip install --insecure openpyxl
    - pip install --insecure $PYRO
    - pip install --insecure coverage
    - python setup.py develop

script:
    - test.pyutilib --cat=nightly --cov

after_success:
    - pip install codecov
    - cp ../.coverage .
    - codecov
    - pip install python-coveralls
    - cp ../.coverage .
    - coveralls
